events {
    worker_connections 1024;
}

http {
    upstream backend_cluster {
        ip_hash;
        server cam1:8000;
        server cam2:8000;
    }

    server {
        listen 8000;

        location / {
            proxy_pass http://backend_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /ws/ {
            proxy_pass http://backend_cluster;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }
}
